- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool-bin, gettext)
  become: true
  apt:
    name:
      - lua5.1
      - unzip
      - libtool-bin
      - gettext
      - ninja-build
  tags:
    - neovim
    - core

- name: Install System Packages 3 ( The rest  )
  become: true
  apt:
    name:
      - curl
      - wget
      - htop
      - lsof
      - pavucontrol
      - dconf-editor
      - moreutils
      - i3
      - python3-pip
      - python3
      - python3.10-venv
      - blueman
      - xclip
  tags:
    - neovim
    - core

- name: Install System Packages 4 (Snap)
  become: true
  snap:
    name:
      - postman
  tags:
    - core

- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-11", "clangd-12"]
  tags:
    - neovim
    - core

- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  apt:
    name: python3-mysqldb
    state: latest

- name: Install Mysql
  become: true
  apt:
    name: mysql-server
  tags:
    - mysql
    - core

- name: Start mysql service
  become: true
  shell: systemctl start mysql.service
  tags:
    - mysql
    - core

- name: Preset for mysql secure installation
  become: true
  community.mysql.mysql_query:
    query: ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
  tags:
    - mysql
    - core

- name: Install font
  become: true
  shell: cp font.otf /usr/share/fonts/opentype/
  tags:
    - core
    - font

- name: Update font cache
  shell: fc-cache -f -v
  tags:
    - core
    - font

- name: Install Chrome
  shell: |
    sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
    wget -O- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo tee /etc/apt/trusted.gpg.d/linux_signing_key.pub
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
    apt-key export D38B4796 | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/chrome.gpg
    apt-get update
    apt-get install google-chrome-stable
  tags:
    - core
    - chrome

- name: Install Discord
  become: true
  community.general.snap:
    name: discord
    classic: true

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - core

- name: Enable auto regulation of cpu
  ansible.builtin.git:
    repo: 'https://github.com/AdnanHodzic/auto-cpufreq.git'
    dest: "{{ lookup('env', 'HOME') }}/auto-cpufreq"
    version: master
  tags:
    - cpu

- name: Enable auto regulation of cpu
  become: true
  shell: |
    cd /home/gaetan/auto-cpufreq 
    ./auto-cpufreq-installer --install
  tags:
    - cpu

- name: Delete auto cpu folder
  become: true
  shell: |
    rm -rf home/gaetan/auto-cpufreq
  tags:
    - cpu
