- name: Install prerequisites
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  tags: docker

- name: Add Docker GPG key to apt
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/trusted.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags: docker

- name: Update apt cache after adding Docker repository
  become: true
  apt:
    update_cache: yes
  tags: docker

- name: Install Docker packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
  tags: docker
