- name: Installing stow
  apt: name=stow
  tags:
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Nuxnuxx/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: main
  tags:
    - dotfiles
    - stow

- name: Cloning nvim in .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Nuxnuxx/nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles/nvim/.config/nvim"
    version: master
  tags:
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./stow.sh
  tags:
    - dotfiles
    - stow

- name: fix xressource not refreshing
  shell: xrdb ~/.Xressources
  tags:
    - dotfiles
    - fix
    - stow

- name: fix script not linking to global
  become: true
  shell: cp /home/gaetan/.dotfiles/bin/.local/scripts/* /usr/local/bin/
  tags:
    - dotfiles
    - fix
    - stow
