- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "nuxnux02290@gmail.com"
  tags:
  - git
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Nuxnuxx"
  tags:
  - git

- name: Install gh cli
  become: true
  apt: name=gh
  tags: 
  - git
