- name: Install neovim
  shell: |
    git clone https://github.com/neovim/neovim.git ~/neovim
    chdir ~/neovim
    git checkout stable
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install
    chdir ~
    rm -rf neovim
  tags:
    - core
    - neovim
