- name: Install Prettier
  shell: npm install prettier -g
  tags:
    - npm

- name: Install eslint
  shell: npm install eslint -g
  tags:
    - npm

- name: Install nodemon
  shell: npm install nodemon -g
  tags:
    - npm
